export function formatReviewComment(report) {
  const {
    repository,
    pullRequest,
    filesScanned,
    issues,
    trustScore,
    riskLevel
  } = report;

  const riskIcon = {
    LOW: "🟢",
    MEDIUM: "🟠",
    HIGH: "🔴"
  };

  let markdown = `# 🤖 Tracr Review

Repository: **${repository}**
Pull Request: **#${pullRequest}**

## Summary

📁 Files Scanned: **${filesScanned}**

${riskIcon[riskLevel]} Overall Risk: **${riskLevel}**

## Findings

`;

  if (issues.length === 0) {
    markdown += "✅ No issues detected.\n";
  } else {
    for (const issue of issues) {
      markdown += `- ${issue.icon} **${issue.title}**\n`;
      markdown += `  - File: \`${issue.file}\`\n`;
      markdown += `  - ${issue.message}\n\n`;
    }
  }

  markdown += `## Trust Score

**${trustScore}/100**

---
Generated by **Tracr**
`;

  return markdown;
}